name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

      - name: Install actionlint
        shell: bash
        run: go install github.com/rhysd/actionlint/cmd/actionlint@v1

      - name: Run actionlint
        shell: bash
        run: actionlint
